### ISSUE TITLE
False positive for Automatic Updates on Mac Mojave 10.14.4

### ISSUE THREAD

**Issue by smarbin** [Netflix-Skunkworks/stethoscope-app#136]
* **I'm submitting a ...**
  - [x] bug report
  
* **What is the current behavior?**
Related to: https://github.com/Netflix-Skunkworks/stethoscope-app/issues/135

On Mac Mojave 10.14.4 with Stethoscope v3.0.4 I'm getting a green check mark and it says "Automatic updates are enabled" even though they are not enabled in the system control panel. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Choose System Preferences from the Apple menu.
2. Click Software Update
3. Uncheck "Automatically check for updates"
4. Click "Rescan" on Stethoscope

* **What is the expected behavior?**
It should show a red X, and say  "Automatic updates are enabled"

* **What is the motivation / use case for changing the behavior?**
Users might be tricked into believing their system is secure when it's not. 

* **Please tell us about your environment:**

  - Stethoscope Version: v3.0.4
  - Platform:
    - [x] Mac Mojave 10.14.4

  - Browser: [x] Chrome Version 73.0.3683.103 (Official Build) (64-bit)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Screenshot showing the automatic updates bug:
![automatic updates bug](https://user-images.githubusercontent.com/20249846/56084965-54ef1680-5df0-11e9-94fc-5d42d674cfb1.png)

**Comment by rmcvey** [comment]
Thanks for reporting, the macOS UI can be a _little_ misleading, curious what you see when you click "Advanced" next to "Automatically keep my Mac up to date". Here's what mine shows after unchecking "Automatically keep..." 
<img width="693" alt="Software_Update" src="https://user-images.githubusercontent.com/307161/56089203-8560a000-5e44-11e9-8a65-6d6e4a989cf9.png">
This still automatically checks for updates and notifies you that they are available, it just doesn't automatically _install_ the updates. This is sufficient for our use case, happy to discuss further if you have thoughts or questions.

**Comment by rmcvey** [comment]
Almost forgot an important point: this still will automatically install system data files and security updates.

**Comment by smarbin** [comment]
Sorry for the delay. When I opened Stethoscope I was prompted to update, so I'm now on  Stethoscope Version: v3.0.5

Digging deeper into software update settings, it looks like as long as "Check for updates" (under Advanced) is checked, Stethoscope shows green and "This device is properly configured." 
If I uncheck "Check for updates" Stethoscope shows yellowish and "The security settings on this device could be improved. Click the arrow next to each recommendation for instructions."

See screenshots attached.

![Screen Shot 2019-05-03 at 9 31 10 AM](https://user-images.githubusercontent.com/20249846/57152499-88d2b180-6d88-11e9-8371-07db460af76b.png)

![Screen Shot 2019-05-03 at 9 30 32 AM](https://user-images.githubusercontent.com/20249846/57152504-8c663880-6d88-11e9-9e95-9c4bb679c0c2.png)

**Comment by rmcvey** [comment]
These settings on Mac end up in a plist file that we inspect to see whether or not Automatic Updates are enabled.  For our use-case at Netflix, we do not consider AutoUpdates being off to be enough to WARN the user and turn the app red (hence seeing the NUDGE state), many users keep their devices up to date manually and don't want unwanted restarts.

Let me know if this doesn't address your concerns.

If you are curious, you can see the Automatic Update checks that we are running here: https://github.com/Netflix-Skunkworks/stethoscope-app/blob/master/sources/darwin/com.apple.SoftwareUpdate.sh#L2-L24

Once that data is retrieved, this is the logic we use to determine if you should see Green (OK) or Yellow (NUDGE) - https://github.com/Netflix-Skunkworks/stethoscope-app/blob/master/resolvers/platform/MacSecurity.js#L28-L53
