### ISSUE TITLE
False positive for "Screen Lock When System Is Idle" on Mac Mojave 10.14.4

### ISSUE THREAD

**Issue by smarbin** [Netflix-Skunkworks/stethoscope-app#137]
* **I'm submitting a ...**
  - [x] bug report
  
* **What is the current behavior?**
Related to: https://github.com/Netflix-Skunkworks/stethoscope-app/issues/135
and https://github.com/Netflix-Skunkworks/stethoscope-app/issues/136

On Mac Mojave 10.14.4 with Stethoscope v3.0.4 I'm getting a green check mark and it says "Screen will lock when the system is idle for too long" even though that is disabled in the system control panel. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Choose System Preferences from the Apple menu.
2. Click Desktop & Screen Saver.
3. Click the Screen Saver tab.
4. Adjust the "Start after" dropdown to "never"
5. Click "Rescan" on Stethoscope

* **What is the expected behavior?**
It should show a red X, and say  "Screen will NOT lock when the system is idle for too long"

* **What is the motivation / use case for changing the behavior?**
Users might be tricked into believing their system is secure when it's not. 

* **Please tell us about your environment:**

  - Stethoscope Version: v3.0.4
  - Platform:
    - [x] Mac Mojave 10.14.4

  - Browser: [x] Chrome Version 73.0.3683.103 (Official Build) (64-bit)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Screenshot showing the bug:
![screen lock when system is idle bug](https://user-images.githubusercontent.com/20249846/56084996-f8d8c200-5df0-11e9-9e6c-c9f4818efbab.png)

**Comment by rmcvey** [comment]
Good find! Will see what we can do to resolve this.
