### ISSUE TITLE
Auto-update appears to hang for Linux AppImages when upgrading from 3.0.4 to 3.0.5

### ISSUE THREAD

**Issue by erichs** [Netflix-Skunkworks/stethoscope-app#138]
**Note: for support questions, please [email us](mailto:stethoscope@netflix.com) or contact us on [Gitter](https://gitter.im/Netflix-Stethoscope/Lobby)**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
Stethoscope is running as currently-logged-in user, launched from Activities menu or via auto-start on boot. When prompted to upgrade to latest version, Electron correctly downloads the necessary files to `~/.config/Stethoscope/__update__`. Then the app flashes a window saying "Updates downloaded, Stethoscope will quit and relaunch."

The app does not quit, however.

Manually quitting the app will allow the update to continue in the background, and the downloaded (in this case 3.0.5 version) app will be moved into its final spot, replacing the previous versions' AppImage file.

Launching Stethoscope manually from the Activities menu at this point starts up 3.0.5 just fine.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

See above.

* **What is the expected behavior?**

The user-owned process started from the 3.0.4 AppImage should close, and automatically launch the 3.0.5 process.

* **Please tell us about your environment:**

  - Stethoscope Version:
  - Platform:
    - [ ] Mac
    - [ ] Windows
    - [x] Linux (Ubuntu 18.04)

**Comment by rmcvey** [comment]
Thanks for reporting @erichs, have you been able to capture any logs (error/debug/etc.) around this? We have observed one issue with updates, but it is specifically when the window is destroyed (closed) and the update process is started via menubar/taskbar [PR here](https://github.com/Netflix-Skunkworks/stethoscope-app/pull/134).

We've observed similar problems in the past on different platforms, but aren't seeing this on Mac or Windows currently.

**Comment by erichs** [comment]
Not sure where to look for logs. I did run the `.AppImage` in the foreground and caught this on stdout:

```
erichs@carbonite:/opt/stethoscope $ ./Stethoscope-3.0.4-x86_64.AppImage 
GraphQL server listening on 37370
Checking for update
Found version 3.0.5 (url: Stethoscope-3.0.5-x86_64.AppImage)
Gtk-Message: 11:17:25.120: GtkDialog mapped without a transient parent. This is discouraged.
Downloading update from Stethoscope-3.0.5-x86_64.AppImage
Update has already been downloaded to /home/erichs/.config/Stethoscope/__update__/Stethoscope-3.0.5-x86_64.AppImage).
Gtk-Message: 11:17:28.405: GtkDialog mapped without a transient parent. This is discouraged.
Checking for update
Found version 3.0.5 (url: Stethoscope-3.0.5-x86_64.AppImage)
Gtk-Message: 11:18:50.840: GtkDialog mapped without a transient parent. This is discouraged.
Downloading update from Stethoscope-3.0.5-x86_64.AppImage
Gtk-Message: 11:18:53.255: GtkDialog mapped without a transient parent. This is discouraged.
Auto install update on quit
Install: isSilent: true, isRunAfter: false
```

I manually triggered an update check, then manually quit the app.

**Comment by erichs** [comment]
I did see a log file here, but it is 0 bytes:
```
erichs@carbonite:~/.config/Stethoscope $ ls -l ~/.config/Stethoscope/
total 56
-rw-r--r-- 1 erichs erichs     0 Apr 17 11:17  application-2019-04-17.log
```

**Comment by rmcvey** [comment]
If you have 3.0.4, you could install it again and launch Stethoscope with the debug flag: 

```bash
STETHOSCOPE_DEBUG=* launch_cmd_on_linux
```
That will enable more verbose logging. syslog sometimes has useful information if there is a crash that the Electron process doesn't have access to/awareness of

**Comment by rmcvey** [comment]
To clarify: you could install 3.0.4 again, launch with debug, start the update and see if anything more useful surfaces in the log

**Comment by erichs** [comment]
I'll try that!

**Comment by erichs** [comment]
Running with STETHOSCOPE_DEBUG=y, I get more details in `/var/log/syslog`:

[log.txt](https://github.com/Netflix-Skunkworks/stethoscope-app/files/3090830/log.txt)

**Comment by rmcvey** [comment]
This seems to be the relevant portion: 

```
failed to rescan: Failed to parse /home/erichs/.local/share/applications/appimagekit-stethoscope.desktop fil
e: cannot process file of type application/x-desktop
```

**Comment by erichs** [comment]
Interesting. That's a file like so:
```
erichs@carbonite:~/.local/share/applications $ ls -lad . appimagekit-stethoscope.desktop 
drwx------ 2 erichs erichs 4096 Apr 17 13:43 .
-rwxr-xr-x 1 erichs erichs  483 Apr 17 13:31 appimagekit-stethoscope.desktop
```

that has contents:
```
[Desktop Entry]
Name=Stethoscope
Comment=Local Stethoscope app
Exec="/opt/stethoscope/Stethoscope-3.0.5-x86_64.AppImage" %U
Terminal=false
Type=Application
Icon=appimagekit-stethoscope
X-AppImage-Version=3.0.5
X-AppImage-BuildId=1be23570-6084-11a9-1bf3-5ff9b43d3d8d
MimeType=x-scheme-handler/stethoscope;
Categories=System;
X-Desktop-File-Install-Version=0.23
X-AppImage-Comment=Generated by /tmp/.mount_StethoEZYn3o/AppRun
TryExec=/opt/stethoscope/Stethoscope-3.0.5-x86_64.AppImage
```

**Comment by erichs** [comment]
Wrong MIME handler?

**Comment by rmcvey** [comment]
Google isn't providing much help so far, I did find this though: https://askubuntu.com/questions/832864/gnome-adding-desktop-for-gnome-menu-not-parsed

**Comment by rmcvey** [comment]
This [post](https://unix.stackexchange.com/questions/156892/how-to-validate-verify-desktop-files) says you can validate `.desktop` files using `desktop-file-validate` tool provided by the [desktop-files-utils package](https://www.freedesktop.org/wiki/Software/desktop-file-utils/)

**Comment by erichs** [comment]
oooh! I'll look into that. Thanks!

**Comment by erichs** [comment]
Strange. The `appimagekit-stethoscope.desktop` validates perfectly with `desktop-file-validate`. The "failure to parse" seems like it may have less to do with validation/syntax and more to do with the second half of the error: `cannot process file of type application/x-desktop`. Or, it could be a red herring.

**Comment by rmcvey** [comment]
Hi @erichs, any luck figuring out the auto update issue? We are rolling out beta linux support internally in the next release and definitely would like to help get this resolved.

**Comment by erichs** [comment]
Sorry! I haven't had an opportunity to look further into this yet.
