### ISSUE TITLE
Packaging practices into folders/modules

### ISSUE THREAD

**Issue by cfarvidson** [Netflix-Skunkworks/stethoscope-app#152]
First of all I just want to say that I'm a big fan of what you guys are doing!

We in the developer experience team at svt.se are looking at how we could build and use Stethoscope internally and contribute to the upstream project.

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**

Creating a new practice and activating that in the policy involves changes across the codebase. 

As seen in this little hello world policy example: https://github.com/SVT/stethoscope-app/commit/b5f086f2eb71d0251d4e102024d374c21ca80612

Included polices are then "activated" in the `src/practices/policy.yaml`

* **Suggested new feature**

It would be nice to have a folder that contained all practices `src/practices/` and a separate folder for each practice (`src/practices/screenLock`, `src/practices/automaticUpdates` etc). 

That folder/module could contain all of the strings, resolvers, graphql, tests etc for that practice.

All practices could then be dynamically loaded at build time based on a `src/practices/policy.yaml`.

The spirit of this is kind of like apps work in the Django framework https://docs.djangoproject.com/en/2.2/intro/tutorial01/#creating-the-polls-app.

* **What is the motivation / use case for changing the behaviour?**

1. We would like to contribute security practices upstream and still be able to add more organization specific security practices without having to deal with too many merge conflicts down the road.

2. Maybe it would be easier to add a new security practice if you could copy and modify a folder containing everything needed for that practice?

3. The continuation of this could maybe be to support the packaging and loading practices as npm packages? 

* **Please tell us about your environment:**

  - Stethoscope Version:
  - Platform:
    - [x] Mac
    - [x] Windows
    - [x] Linux

**Comment by rmcvey** [comment]
This is a really great idea and I think it makes a lot of sense to move in this direction. We are discussing what would need to change to make this work (we have other internal projects that share code with this).
