### ISSUE TITLE
Improve "new version available" dialog

### ISSUE THREAD

**Issue by jkriss** [Netflix-Skunkworks/stethoscope-app#160]
**I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

**What is the current behavior?**

![image](https://user-images.githubusercontent.com/6276/61563746-8435a500-aa29-11e9-9683-6d4653d39dd7.png)

This dialog comes up when an update is available.

**What is the expected behavior?**

* The window should have a title, something like "Stethoscope update available"
* "do you want update now" should be "do you want *to* update now" (Maybe even better: "A new version is available, would you like to download and update?"
* The "Yes" button should be styled as a primary action

Additionally, it might be clearer to have more action oriented button labels, like "Update now" and "Not now". (Relatedly: what happens if people decline to update? Does this prompt come up again later, or does it stay quiet until the next version comes out?)

**What is the motivation / use case for changing the behavior?**

Fixing the typo, plus generally improving clarity of message and actions.

**Please tell us about your environment:**

  - Stethoscope Version: 3.1.0
  - Platform:
    - [x] Mac
    - [x] Windows
  - Browser: [n/a]

**Comment by nathancharles** [comment]
Unfortunately, the dialog title showing is platform dependent and it seems that Mac hides it
> Title of the message box, some platforms will not show it.

I've updated the messaging to be more clear and use yes as the defaulted button
