### ISSUE TITLE
Potential issue with Open Wifi scan

### ISSUE THREAD

**Issue by dryan** [Netflix-Skunkworks/stethoscope-app#161]
**Note: for support questions, please [email us](mailto:stethoscope@netflix.com) or contact us on [Gitter](https://gitter.im/Netflix-Stethoscope/Lobby)**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
Wifi scan tells me I have open networks, I went to the System Preferences and remove the 3 marked Open. Stethoscope still says I have open networks. And looking at the airport plist file, it contains 300+ total networks, while the preference pane shows 4.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
I'm not sure if this is a bug or if it's a documentation issue.

* **What is the expected behavior?**
Following the instructions for fixing a failed check should let the check pass.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Stethoscope Version:
  - Platform:
    - [x] Mac
    - [ ] Windows
  - Browser: N/A

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

<img width="780" alt="Screen Shot 2019-07-22 at 12 37 57 PM" src="https://user-images.githubusercontent.com/15066/61648515-927bff00-ac7d-11e9-95dd-e19e26d0b55b.png">

I can provide my plist as well if that's helpful.

**Comment by jkriss** [comment]
@cfarvidson, do you have any insight into the difference between the Network preference pane and the plist? In the meantime, @dryan, you could remove the open wifi part from your policy file.

**Comment by cfarvidson** [comment]
I think that this is a Mac issue and that the Stethoscope warning is correct. My guess is that in some cases the plist and the GUI gets out of sync with each other. 

Two colleagues of mine have had the same issue. 

The WiFi's in question was deleted in the GUI but remained in the plist. (Triggering Stethoscope to nudge the user to clear the settings). 

The weirdest thing on one of the Macs was that with the GUI completely cleared the Mac still connected to a previously known WiFi. (That lead me to believe that it's the plist that's the source of truth and that this is a rare Mac WiFi issue)

In both cases we resorted to deleting the plist and then rebooted. 

The Mac then stopped connecting to the WiFi that should have been forgotten in the first place and stethoscope stopped warning. 🎉

The following link describes how to do this: 
http://osxdaily.com/2018/11/19/fix-macos-mojave-wifi-problems/ (see *Make a New Wi-Fi Configuration in MacOS Mojave*)

The link above deletes more plist files but I think that we just deleted the plist that Stethoscope checks.

Maybe the help text should be updated to also include a link or a terminal rm command + reboot instruction.

**Comment by cfarvidson** [comment]
@dryan do you use the locations feature in networks? Are there multiple users on your Mac?

I’m just curious. 🙂

**Comment by dryan** [comment]
> @dryan do you use the locations feature in networks? Are there multiple users on your Mac?
> 
> I’m just curious. 🙂

I have used locations in the past, but not on this computer. Wouldn't surprise me though if some of that data is lingering in my account. There are multiple users on this machine as well.

**Comment by dryan** [comment]
Removing the plist and rebooting did clear up the warning. I think for non-technical users running a Terminal command is probably a non starter. I'm wondering if it would worth filing some radars with Apple about this?

**Comment by mutewinter** [comment]
This is definitely still an issue. Rolled v4.0.1 out today to our org and had numerous reports of this.

**Comment by cfarvidson** [comment]
I'm not 100% sure but I think that the check in Stethoscope does what it's suppose to do. But that there might be some bug with the presentation in the preference panel. 

But that's based on us seeing that one laptop connected to a network that was not present in the preferences but was found in the plist.

I could also be wrong..And there was something else causing that behavior.

I'm wondering if maybe a tool like **CleanMyMac X** sees the open networks even if they are not displayed in System Preferences -> Network?

On [this page](https://macpaw.com/how-to/fix-macos-catalina-problems#wi-fi-issues-on-macos-catalina) there is a more user friendly alternative. (Under *9. Wi-Fi issues on macOS Catalina -> Alternative fix with CleanMyMac X*.

Another alternative would be to add a clean button to stethoscope or to build a separate user-friendly tool just for the wifi cleaning.

Or filing a bug report with Apple.
