### ISSUE TITLE
Applications should support platform filter

### ISSUE THREAD

**Issue by erichs** [Netflix-Skunkworks/stethoscope-app#169]
**Note: for support questions, please [email us](mailto:stethoscope@netflix.com) or contact us on [Gitter](https://gitter.im/Netflix-Stethoscope/Lobby)**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
The `requiredApplications` mechanism from 3.0 series supported a `platform` filter: https://github.com/Netflix-Skunkworks/stethoscope-app/blob/ef73fcf4e5e50fc669773ef933fa4d1c25fd199c/schema.graphql#L138.

This enabled one policy to span multiple OS platforms, and the version and installation assertions would only apply if Stethoscope was running on the listed platform.

The new mechanism does not appear to support this: https://github.com/Netflix-Skunkworks/stethoscope-app/blob/c4d5dd97f82b736e6d8a4d48a5840b3bd3b6e184/schema.graphql#L112-L119

* **Please tell us about your environment:**
As this is a breaking GraphQL schema change, it affects all platforms. Additionally, the Platform-specific resolvers should have code added to filter out and resolve only the ApplicationRequirements specific to their platform. The WindowsSecurity resolver currently appears to try to account for this: 
https://github.com/Netflix-Skunkworks/stethoscope-app/blob/c4d5dd97f82b736e6d8a4d48a5840b3bd3b6e184/src/resolvers/platform/WindowsSecurity.js#L70-L81 (though I have only quickly glanced at this code)

- Stethoscope Version:
  - Platform:
    - [ ] Mac
    - [ ] Windows
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by nathancharles** [comment]
Addressed in #172
