### ISSUE TITLE
Linux disk block volume information is spammy

### ISSUE THREAD

**Issue by erichs** [Netflix-Skunkworks/stethoscope-app#178]
**Note: for support questions, please [email us](mailto:stethoscope@netflix.com) or contact us on [Gitter](https://gitter.im/Netflix-Stethoscope/Lobby)**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
For modern Ubuntu systems, [Snap-format](https://snapcraft.io/docs/getting-started) applications are often used alongside the traditional Debian packages (`apt`). These applications use `squashfs` internally as a read-only filesystem, and result in many, many mounted loopback filesystems of type `"squashfs"` when examined with a command like `lsblk`, which the kmd script in the linux disk resolver uses.

* **What is the expected behavior?**
Users of Stethoscope almost certainly aren't interested in this volume information when considering the current state of the endpoint's disks. They should be removed from the output.

* **Please tell us about your environment:**

  - Stethoscope Version:
  - Platform:
    - [ ] Mac
    - [x] Windows
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by erichs** [comment]
I believe this is closed as of commit 3c1ed6a4eb8a4f967a919d63fdd26ec1322e9627.

**Comment by nathancharles** [comment]
> I believe this is closed as of commit [3c1ed6a](https://github.com/Netflix-Skunkworks/stethoscope-app/commit/3c1ed6a4eb8a4f967a919d63fdd26ec1322e9627).

Thanks for following up on this! I must have not seen the issue
