### ISSUE TITLE
Linux: Clicking red X in electron app quits Stethoscope instead of minimizing to tray

### ISSUE THREAD

**Issue by erichs** [Netflix-Skunkworks/stethoscope-app#192]
**Note: for support questions, please [email us](mailto:stethoscope@netflix.com) or contact us on [Gitter](https://gitter.im/Netflix-Stethoscope/Lobby)**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
Clicking red X in 4.0.0 / 4.0.1 electron app quits Stethoscope instead of minimizing to tray

* **Please tell us about your environment:**

  - Stethoscope Version:
  - Platform:
    - [ ] Mac
    - [ ] Windows
    - [x] Linux

**Comment by rmcvey** [comment]
Thanks for the report, looking into this now.

**Comment by rmcvey** [comment]
@erichs would you mind running a test build of https://github.com/Netflix-Skunkworks/stethoscope-app/pull/193 and seeing if it resolves this issue?

**Comment by erichs** [comment]
Thanks! Sorry I didn't have my linux laptop handy over the holidays.
