### ISSUE TITLE
SemVer comparison not working as expected

### ISSUE THREAD

**Issue by ericofusco** [Netflix-Skunkworks/stethoscope-app#199]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**

OS version comparison is not working as expected. Tested on Windows.

Policy configured:

```
...
  win32:
    ok: ">=10.0.18363"
    nudge: ">=10.0.17763"
...
```
Windows OS Version: **10.0.19041**

Screenshot:
![Capture](https://user-images.githubusercontent.com/5590224/83665870-f7a1c000-a5c3-11ea-860c-5a75ade5d07b.PNG)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Add the policy mentioned in the bug report.
Run stethoscope on Windows with the latest OS Version **10.0.19041**.

* **What is the expected behavior?**

Pass the policy configured with the latest OS Version.

* **Please tell us about your environment:**

  - Stethoscope Version: 5.0.0
  - Platform:
    - [ ] Mac
    - [x] Windows
  - Browser: all

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by rmcvey** [comment]
Hi @ericofusco, thanks for submitting this issue! 

I'm looking into this. All we are doing is a basic semver comparison (which works when I run it manually), so I'm not sure how or why this would be failing. 

```
> semver.satisfies('10.0.19041', ">=10.0.18363")
true
```

Will work on reproducing.

**Comment by ericofusco** [comment]
Thanks for checking @rmcvey. It looks like it's really not an issue with semver. I hardcoded the OS version on my mac and it worked just fine, it might be something related to the value pulled for WIndows and what's compared. I'll see if I cab debug this when I get a chance and let you know.
