### ISSUE TITLE
DISCUSSION: On Darwin, leverage/convert/borrow logic for static macmodels.js from https://github.com/MagerValp/MacModelShelf

### ISSUE THREAD

**Issue by arubdesu** [Netflix-Skunkworks/stethoscope-app#30]
* **I'm submitting a ...**
  - [√] feature request... kinda?
(I caught y'all on the way out the door at querycon, before I knock y'all over the head with feature requests to run arbitrary mgmt tool health checks to display in stethoscope...)
* **What is the current behavior?**
https://github.com/Netflix-Skunkworks/stethoscope-app/blob/21fd92d4cff9625507ea567e8d6cab44624e15d8/sources/macmodels.js stores the (I'm assuming manually updated?) static file of models instead of leveraging a db or doing a web call to lookup the model in case of a 'cache miss'

* **What is the expected behavior?**
I'm not saying/suggesting fire up python for this, but leverage the already-done work gathered in that repo to maybe add that db as a backend instead of the flat file, and as a fallback query Apple's long-standing... semi-official 'API'
https://github.com/MagerValp/MacModelShelf/blob/master/macmodelshelf.py#L42
I've hit Apple's site from that modified code hundreds of times over the past year with internal tooling...

* **What is the motivation / use case for changing the behavior?**
While your data structure in the flat file is _probably_ fine from a performance standpoint, being able to do a lookup if you get a miss from the static cache may be desirable. And more folks aware of the work Per's done/contributing to it would be cool! 

* **Please tell us about your environment:**
  - Platforms:
    - Predominately Mac
    - 4-digit workstation Linux
    - Rounding error Windows

  - Stethoscope (App) Version: initial release June 2018

**Comment by rmcvey** [comment]
Thanks for opening the issue @arubdesu, I remember speaking with you at QueryCon and I'm glad to see you here!

I agree that it would be better to pull this data from an authoritative source and would be a bonus to leverage existing work. The reasoning behind our current flat-file approach is that we don't want the application making network requests \*

Though we haven't open-sourced the app builder, I think it would make a lot of sense to use [MacModelShelf](https://github.com/MagerValp/MacModelShelf) to fetch and write an updated database before building/signing the binaries and I will likely explore that.

\* It is important to us to produce an app that can run on anyone's computer regardless of internet connection, and we really want users to trust that everything that is happening is staying on their machine.
