### ISSUE TITLE
requiredApplications is not functional

### ISSUE THREAD

**Issue by Popsiclestick** [Netflix-Skunkworks/stethoscope-app#31]
* **I'm submitting a ...**
  - [X] bug report

* **What is the current behavior?**

When attempting to use `required applications` we receive `Device.applications is not a function`.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

You can cause this by attempting to use `required applications` policy key inside of policy.yaml
```
required applications:
- name: Google Chrome
```
You can attempt to console the Device object.
```
  async requiredApplications (root, args, context) {
    console.log(Device)
    const applications = await Device.applications(root, args, context)
    ...
    ...
  }
```

* **What is the expected behavior?**

It should return a non-empty object.

* **Please tell us about your environment:**

  - Stethoscope Version: 1.1.7
  - Platform:
    - [ X ] Mac

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

It appears as though /resolvers/platform/MacSecurity.js file isn’t properly importing `Device` from /resolvers/Device.js. If I just console.log Device within MacSecurity it just outputs an empty object {}. I looked into this issue and I’m assuming it might be a circular dependency according to this stackoverflow post: https://stackoverflow.com/questions/23875233/require-returns-an-empty-object/23875299

**Comment by rmcvey** [comment]
I have a fix for the error in this branch: https://github.com/Netflix-Skunkworks/stethoscope-app/tree/issue-31; however, it is not ready to merge into `master` due to the fact that we don't have the necessary code in place to display actionable results based on this information.

The branch is available to check out if you want to mess around with this feature. There is another branch that we are working on getting into `master` - https://github.com/Netflix-Skunkworks/stethoscope-app/tree/templated_instructions - that I think is closely related to this, since the `templated_instructions` branch allows us to iterate through results in the instructions using Handlebars, e.g. 

```markdown
diskEncryption:
  title: >
    {{#if passing}}
      Disk Encryption is enabled
    {{else}}
      Disk Encryption should be enabled
    {{/if}}
  description: >
    Full-disk encryption protects data at rest from being accessed by a party who does not know the password or decryption key. Systems containing internal data should be encrypted. It is every employee's responsibility to keep internal data safe.
  directions:
    darwin: |
      1. Choose System Preferences from the Apple menu.
      1. Click [Security or Security & Privacy](x-apple.systempreferences:com.apple.preference.security).
      1. Click the [FileVault](x-apple.systempreferences:com.apple.preference.security?FDE) tab.
      1. Unlock the pane by clicking the lock in the lower-left corner and enter the administrator username and password.
      1. Click "Turn On FileVault" to start the process.
      {{#each disks}}
        <li>
          {{#if this.encrypted}}
            {{{okIcon this.label}}}
          {{else}}
            {{{warnIcon this.label}}}
          {{/if}}
        </li>
      {{/each}}
```

**Comment by Popsiclestick** [comment]
Awesome! Do you believe that the bulk of the work required to merge `issue-31` into `master` will be completed in `templated_instructions` or will it require work outside of that branch?

**Comment by rmcvey** [comment]
This is fixed in https://github.com/Netflix-Skunkworks/stethoscope-app/pull/51

**Comment by rmcvey** [comment]
Merged.
