### ISSUE TITLE
screenlock security values are not accurate

### ISSUE THREAD

**Issue by groob** [Netflix-Skunkworks/stethoscope-app#33]
Apple has moved these values to the local keychain, so reading them from preferences is no longer returning accurate data. 
Enforcing them via a profile also only starts to take effect _after_ the user logs out once. 

I wrote a detailed blog post about this:
https://blog.kolide.com/screensaver-security-on-macos-10-13-is-broken-a385726e2ae2

**Comment by groob** [comment]
Thanks for the explanation @rmcvey.
What does `UNKNOWN` translate to in the menubar app UI? As a pass or fail?

**Comment by rmcvey** [comment]
No problem 👍 

It depends on the policy, for instance: 

**If the policy is `screenLock: IF_SUPPORTED`** 

`UNKNOWN` translates to `PASS` status in the policy result, which is reflected the UI and the API response. Though the syntax of this query is not _completely_ accurate, this should demonstrate:

Policy query:
```graphql
query {
   validate({ screenLock: IF_SUPPORTED }) {
       status
       screenLock
   }
}
```

API response:
```javascript
{ 
    "data": {
         "validate": {
             "status": "PASS",
             "screenLock": "UNKNOWN"
         }
    }
}
```

**If the policy is `screenLock: ALWAYS`**
`UNKNOWN` translates to a `FAIL` status in the policy result

Policy query:
```graphql
query {
   validate({ screenLock: ALWAYS }) {
       status
       screenLock
   }
}
```

API response:
```javascript
{ 
    "data": {
         "validate": {
             "status": "FAIL",
             "screenLock": "UNKNOWN"
         }
    }
}
```

Hopefully this clarifies things and makes sense. We chose this setup to keep the things we surface to users directly actionable, we've discussed surfacing items that we don't know the state of differently in the UI, but have yet to reach a consensus on the best way to do this.

**Comment by groob** [comment]
That makes sense, thanks for the explanation @rmcvey!

**Comment by arubdesu** [comment]
I'm going to rehash this just briefly to debate with @groob in public (❤️ you, Victor)... could we consider bundling extensions like the [profiles](https://github.com/andrew-d/osquery-profiles) one to detect if it's enforced? Even with the timing issue, that's what I think most orgs would consider 'compliance' - presence of profile that has 'enforced' the setting.
I, of course have other extensions I'd like to leverage...
