### ISSUE TITLE
Templated os queries

### ISSUE THREAD

**Issue by pavarnos** [Netflix-Skunkworks/stethoscope-app#35]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **Do you want to request a *feature* ?**

Thanks so much for creating this project. It will be really helpful for us (as a non profit concerned about operational security). The ability to query the app from a web site is very cool...

Can I suggest an extension to your "templated_instructions" branch? What about adding templated os queries? So the os query for pass / fail for each branch is included in the instructions.yaml for each platform. This will allow you to add new checks very quickly without writing new code for each check, and it will make the tool much more flexible for organisations requiring a different suite of checks.

**Comment by andrewmwhite** [comment]
Thanks for the suggestion. We're still thinking about how to handle this sort of functionality and we'll take this into account.

**Comment by rmcvey** [comment]
Closing since we have moved away from osquery and now support templating in the instructions file.
