### ISSUE TITLE
Check for Updates menu location consistancy

### ISSUE THREAD

**Issue by dryan** [Netflix-Skunkworks/stethoscope-app#41]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **What is the current behavior?**

On Mac build, "Check for Updates" is under the Stethoscope menu; on Windows it's under the Help menu. I'd like to suggest having Check for Updates appear under Help on Mac as well as under the Stethoscope menu. Makes telling users where to look for it consistent.

* **Please tell us about your environment:**

  - Stethoscope Version: 1.2.0
  - Platform:
    - [x] Mac
    - [x] Windows
  - Browser: N/A

**Comment by rmcvey** [comment]
Hi @dryan,

Good point, it would definitely be best to have consistent menus across platforms. One thing to note is that we are currently working on moving the application to the tray, the menu will be accessible only via right-click of the tray icon and will be the same across platforms. Here is an example:

![mac screenshot](https://slack-imgs.com/?c=1&url=https%3A%2F%2Fwww.evernote.com%2Fl%2FAfg2Ox1G-zdPjqu4qMlt3PcpjPEUC14YaFsB%2Fimage.png)

![windows screenshot](https://slack-imgs.com/?c=1&url=https%3A%2F%2Fwww.evernote.com%2Fl%2FAfhtsxsu6otKl4xWnWlNtciO40yCm6_FazAB%2Fimage.png)

The changes are currently in the `tray-only-app` branch and are slated for release in the next major version (1.3.0). If you want to check out the updates and test: https://github.com/Netflix-Skunkworks/stethoscope-app/tree/tray-only-app

**Comment by dryan** [comment]
Sweet! I'll check out that branch over the weekend.
