### ISSUE TITLE
Updated instructions for "Automatic Updates are enabled" for macOS Mojave

### ISSUE THREAD

**Issue by dryan** [Netflix-Skunkworks/stethoscope-app#47]
* **I'm submitting a ...**
  - [x] bug report

* **What is the current behavior?**

Currently in macOS Mojave the instructions say to go to the App Store preference pane. In Mojave this has changed to a new Software Update preference pane.

<img width="780" alt="screenshot 2018-08-23 12 44 23" src="https://user-images.githubusercontent.com/15066/44539486-4a9dd200-a6d2-11e8-8a8f-964b473535e5.png">

Here's the Advanced options as well:
<img width="780" alt="screenshot 2018-08-23 12 44 29" src="https://user-images.githubusercontent.com/15066/44539512-55586700-a6d2-11e8-852a-aa9009bc92c1.png">

* **Please tell us about your environment:**

  - Stethoscope Version: 1.2.5
  - Platform:
    - [x] Mac

**Comment by rmcvey** [comment]
Thanks for opening this issue @dryan! Will take a look on my Mohave machine as soon as I can.
