### ISSUE TITLE
Missing instructions for Automatic Updates

### ISSUE THREAD

**Issue by dryan** [Netflix-Skunkworks/stethoscope-app#48]
* **I'm submitting a ...**
  - [x] bug report

* **What is the current behavior?**

The instructions under automaticUpdates for darwin end with "Make sure the following are checked:" but do not display the sub bullets

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Click the disclosure triangle for Automatic Updates after a scan completes.

* **Please tell us about your environment:**

  - Stethoscope Version: 1.2.5
  - Platform:
    - [x] Mac

**Comment by rmcvey** [comment]
Thanks, we are aware of this issue and are working on a fix for it. Will track the work in here.

**Comment by rmcvey** [comment]
Merged.
