### ISSUE TITLE
Provide signed builds?

### ISSUE THREAD

**Issue by deviantintegral** [Netflix-Skunkworks/stethoscope-app#50]
* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request
  - [ ] support request

It would be great if signed builds for Windows and macOS could be provided. Building locally is easy, but getting Mac and Windows certificates is a hurdle for teams who aren't developing on those platforms. Since I assume the maintainers already have certificates available, it'd be appreciated if they could use them to publish builds.

* **What is the motivation / use case for changing the behavior?**

Not only will this give a good way for teams to demo Stethoscope without code signing warnings, teams who don't need to change the default configs can use the builds directly.

**Comment by rmcvey** [comment]
Thanks for opening an issue @deviantintegral, this is something we have discussed internally in the past. I will bring it up to the team in our next meeting.

**Comment by rmcvey** [comment]
Hi @deviantintegral, we still are deciding about the best path forward on this. In the meantime, an early adopter of Stethoscope, Ragtag, has made a signed public build that anyone can download and try out: https://ragtag.org/stethoscope/

I'm going to close this for now as I think we are still a ways off from moving toward Netflix signed public builds.

**Comment by deviantintegral** [comment]
Thank you!
