### ISSUE TITLE
Ubuntu issue

### ISSUE THREAD

**Issue by kelleyblackmore** [Netflix-Skunkworks/stethoscope-app#73]
I ran this on my ubuntu desktop, my firewall is enabled but the application doesn't detect that it is.
All the other checks ran and completed with green checks.
I did run 'sudo ufw status' to make sure it was running.

Here is my system: 
Linux kitfox-laptop 4.18.11-041811-generic #201809290731 SMP Sat Sep 29 11:33:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

  - Stethoscope Version: v2.0.8
  - Platform:
    - [X] Ubuntu
    - [ ] Mac
    - [ ] Windows
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by erichs** [comment]
Hi, @kelleyblackmore I'm curious what the output of `lsb_release -a` says on your machine?

**Comment by kelleyblackmore** [comment]
@erichs 

LSB Version:	core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

**Comment by erichs** [comment]
Thanks @kelleyblackmore! This appears to be an upstream osquery issue. The `iptables` table appears to be empty (when it is not) for Osquery 3.2.6 and 3.3.0 (latest).

UFW is a wrapper around iptables, and with `ufw status` set to enabled, a command like `iptables -L -V -n` will show many chains, yet the osquery command `SELECT * from iptables;` will return a null set.

I'll check to see if any issues have been opened for this upstream (likely).

**Comment by erichs** [comment]
Oddly enough, it didn't look like that had been reported yet, so I opened an issue: https://github.com/facebook/osquery/issues/5279. @kelleyblackmore FYI.

**Comment by kelleyblackmore** [comment]
When I was looking down the rabbit hole. It seemed something with that library was the issue. Thanks for taking the plunge

**Comment by erichs** [comment]
@kelleyblackmore I forgot that `osquery` requires `root` privileges on Linux in order to access the `iptables` information (to determine the firewall rules in place). This is a known rough-edge with Linux support. If you want to experiment with the service locally, you can do `sudo yarn start` to bring Stethoscope up in dev mode, and the firewall status should reflect reality at that point.

**Comment by rmcvey** [comment]
@kelleyblackmore, I know it's been a while since you first posted this issue - but I am closing this issue now that osquery is no longer used and basic linux support is present thanks to @erichs
