### ISSUE TITLE
Remote login enabled should result in a yellow suggestion (vs red warning)

### ISSUE THREAD

**Issue by andrewmwhite** [Netflix-Skunkworks/stethoscope-app#74]
Dropping this here so it doesn't get lost.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
"Remote Login Disabled" should be yellow if remote login is enabled on the machine, not red. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Enable remote login on macOS.

* **What is the expected behavior?**

Should be a yellow result, not ned.

* **What is the motivation / use case for changing the behavior?**

"Remote Login" is something we want to encourage people to disable if not needed but there are plenty of valid use-cases and we shouldn't block/nag unnecessarily.

* **Please tell us about your environment:**

  - Stethoscope Version: 2.0.8
  - Platform:
    - [x] Mac
    - [ ] Windows
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by rmcvey** [comment]
This is resolved.

**Comment by Sayavong006** [comment]
I found this on my phone and had to find out what's going on, is this spam?


Dear Client,Your Apple ID (sayavong_thong@yahoo.com) was used to sign in to FaceTime, iCloud, and iMessage on an iPhone 6S named “rmcvey’s iPhone”.
--

**Comment by rmcvey** [comment]
Not sure why you received this message but this must be from a different “rmcvey” - I don’t own an iPhone 6s

**Comment by Sayavong006** [comment]
Ok, thank you, I was wondering why I kept getting this message and someone keeps hacking into my phone.  Thank you for getting back to me
