### ISSUE TITLE
Missing deviceName field on Mac

### ISSUE THREAD

**Issue by erichs** [Netflix-Skunkworks/stethoscope-app#83]
**Note: for support questions, please [email us](mailto:stethoscope@netflix.com) or contact us on [Gitter](https://gitter.im/Netflix-Stethoscope/Lobby)**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
deviceName is `""`

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
query ValidateDevice with the app in development mode, observe the output like:

```
   "device": {
      "deviceId": "<redacted>",
      "deviceName": "",
      "platform": "darwin",
      "platformName": "Apple Inc.",
      "osVersion": "10.12.6",
```

* **What is the expected behavior?**
deviceName should not be empty string. This occurs because `computer_name` from osquery `system_info` table is null.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Stethoscope Version: 2.1.0
  - Platform:
    - [x] Mac
    - [ ] Windows
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

osqueryd_version: 3.3.0
osx: 10.12.6

**Comment by rmcvey** [comment]
Merged into master
