### ISSUE TITLE
False positive for disk encryption on Windows

### ISSUE THREAD

**Issue by deviantintegral** [Netflix-Skunkworks/stethoscope-app#89]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**

Note this is not a duplicate of #87 as that applies to newer Apple hardware in macOS only.

On Windows with version 2.1.0 disk encryption is reported as enabled when it's not. For myself, I have an external drive with Bitlocker on but the system drive has no encryption (it's a Bootcamp partition and encryption isn't supported). A coworker (who was only using 2.0.4) reported the same issue, and AFAIK they don't have any Bitlocker drives on their system. Neither system shows Bitlocker enabled in the Control Panel.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Run Stethoscope 2.1.0 and note that disk encryption is reported as enabled when it's not.

* **What is the expected behavior?**

The encryption check should fail.

* **Please tell us about your environment:**

  - Stethoscope Version: 2.1.0
  - Platform:
    - [ ] Mac
    - [x] Windows 10, 1809

**Comment by rmcvey** [comment]
Hi @deviantintegral, thanks for filing this issue. We are moving away from osquery and have a new means of determining windows disk encryption that is much more reliable. We are working on an open-source release of our osquery replacement and will merge the `kmd` branch that no longer uses osquery into master. Closing this issue as it is resolved by the upcoming release.
