### ISSUE TITLE
v2.1.0 fails to run on Win10

### ISSUE THREAD

**Issue by erichs** [Netflix-Skunkworks/stethoscope-app#91]
**Note: for support questions, please [email us](mailto:stethoscope@netflix.com) or contact us on [Gitter](https://gitter.im/Netflix-Stethoscope/Lobby)**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
running `yarn build:windows` fails to launch Stethoscope during Spectron tests, WMI Provider host task consumes 100% CPU, and system becomes unresponsive.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Windows 10 Pro, Version 1803, build 17134.523
Node v10.15.1 LTS
checkout master
yarn build:windows

* **What is the expected behavior?**
Stethoscope should launch

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Stethoscope Version: 2.1.0
  - Platform:
    - [ ] Mac
    - [x] Windows
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Several black console host windows spawn, and seem to hang. The electron dialog never really fully loads, but does eventually throw up a dialog showing a 404 attempting to discover the latest release in latest.yml. Since I did not provide a custom `build.publish`  stanza in `package.json`, this results in the Electron app attempting to download from `https://github.com/Netflix-Skunkworks/stethoscope-app/downloads/v2.1.0/...` which is, indeed, a 404.

I'm not sure if the above is a red-herring, as I imagine it would be non-blocking. I suspect there may be something going on with `osqueryd.exe` initialization, as I saw many "console host" and "taskkill.exe" processes in task manager during this.

**Comment by rmcvey** [comment]
Hello @erichs! We are aware of this issue and have been dealing with it internally :( - this is really the main reason for moving away from osquery. I don't think we are going to attempt to fix this issue in the osquery branches (master/etc.); however, I'm planning on releasing kmd open source tomorrow and will publish on npm so that you can give that a try and see if it works for you.

**Comment by erichs** [comment]
Fantastic, good to hear!
